using UnityEngine;
using UnityEditor;
using System.Linq;

public class MaterialReplacementTool : EditorWindow
{
    //generated by ai because im lazy
    [MenuItem("MakiGriever/Replace Ocean Materials")]
    private static void ReplaceOceanMaterials()
    {
        // Get all selected objects including children
        var selectedObjects = Selection.gameObjects;
        var allMeshRenderers = selectedObjects
            .SelectMany(obj => obj.GetComponentsInChildren<MeshRenderer>(true))
            .ToArray();

        if (allMeshRenderers.Length == 0)
        {
            Debug.LogWarning("No MeshRenderers found in selection!");
            return;
        }

        // Find the replacement material
        string replacementPath = "Assets/Manual/Textures/wmset_9_Material.mat";
        Material replacementMaterial = AssetDatabase.LoadAssetAtPath<Material>(replacementPath);

        if (replacementMaterial == null)
        {
            Debug.LogError($"Replacement material not found at path: {replacementPath}");
            return;
        }

        int replacementCount = 0;
        
        // Start recording undo
        Undo.RecordObjects(allMeshRenderers, "Replace Ocean Materials");

        foreach (var renderer in allMeshRenderers)
        {
            Material[] materials = renderer.sharedMaterials;
            bool materialChanged = false;

            for (int i = 0; i < materials.Length; i++)
            {
                if (materials[i] != null && materials[i].name.Contains("Material_20_ocean"))
                {
                    materials[i] = replacementMaterial;
                    materialChanged = true;
                    replacementCount++;
                }
            }

            if (materialChanged)
            {
                renderer.sharedMaterials = materials;
                EditorUtility.SetDirty(renderer);
            }
        }

        if (replacementCount > 0)
        {
            Debug.Log($"Replaced {replacementCount} ocean material instances.");
        }
        else
        {
            Debug.Log("No ocean materials found in selection.");
        }
    }
}